{% set version = "0.3.3" %}

package:
  name: axe
  version: {{ version }}

build:
  number: 0
  noarch: generic

source:
  url: https://github.com/kdm9/axe/archive/refs/tags/{{ version }}.tar.gz
  sha256: a37afa00decb99fe41be1f2e0a3f982dd3e1192e26de0cf88a0f1362aa1837b2

requirements:
  build:
    - make
    - cmake
    - {{ compiler('c') }}
  host:
    - zlib
  run:
    - zlib

about:
  home: https://github.com/kdm9/axe
  license: GPLv3
  license_file: LICENSE.txt
  summary: De-multiplex NGS reads using trie data structures. It's fast, and made of tries!

test:
  commands:
    - axe-demux --help

extra:
  identifiers:
    - biotools:axe
